export const CLOSE_CREATE_MODE = 'CLOSE_CREATE_MODE'

export const CREATE_NEW_TODO = 'CREATE_NEW_TODO'

export const DELETE_DONE_ITEM = 'DELETE_DONE_ITEM'

export const DELETE_TODO_ITEM = 'DELETE_TODO_ITEM'

export const EDIT_ITEM_DESCRIPTION = 'EDIT_ITEM_DESCRIPTION'

export const MARK_ITEM_UNDONE = 'MARK_ITEM_UNDONE'

export const MARK_TODO_AS_DONE = 'MARK_TODO_AS_DONE'

export const OPEN_CREATE_MODE = 'OPEN_CREATE_MODE'

export const SET_INITIAL_DATA = 'SET_INITIAL_DATA'
